version: '3'

services:
  db:
    image: docker.io/postgres:latest
    volumes:
      - npi_files_dbdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    env_file:
      - backend/.env

  django_app:
      container_name: django-app
      build: .
      image: npi_backend:latest
      ports:
        - 8080:8000

  # frontendapp:
  #     container_name: frontend-container
  #     build: ./Frontend
  #     image: frontend:v1
  #     ports:
  #       - 4200:4200
  #     expose:
  #       - 4200
    
volumes:
  npi_files_dbdata:
    