version: '3'

services:
  db:
    image: docker.io/postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    env_file:
      - src/.env

  frontendapp:
      container_name: frontend-container
      build: ./Frontend
      image: frontend:v1
      ports:
        - 4200:4200
      expose:
        - 4200
    
volumes:
  dbdata:
    